-- Generated by Matugen
require("base16-colorscheme").setup({
	base00 = "{{colors.surface.default.hex}}",
	base01 = "{{colors.surface_container.default.hex}}",
	base02 = "{{colors.surface_container_high.default.hex}}",
	base03 = "{{colors.outline.default.hex}}",
	base04 = "{{colors.on_surface_variant.default.hex}}",
	base05 = "{{colors.on_surface.default.hex}}",
	base06 = "{{colors.on_surface.default.hex}}",
	base07 = "{{colors.on_background.default.hex}}",
	base08 = "{{colors.error.default.hex}}",
	base09 = "{{colors.tertiary.default.hex}}",
	base0A = "{{colors.secondary.default.hex}}",
	base0B = "{{colors.primary.default.hex}}",
	base0C = "{{colors.tertiary_fixed_dim.default.hex}}",
	base0D = "{{colors.primary_fixed_dim.default.hex}}",
	base0E = "{{colors.secondary_fixed_dim.default.hex}}",
	base0F = "{{colors.error_container.default.hex}}",
})

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "{{colors.primary_fixed_dim.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}", -- normal text contrast
})

-- Make current-line highlight easier to see, but subtle
vim.api.nvim_set_hl(0, "CursorLine", {
	bg = "{{colors.secondary_fixed_dim.default.hex | lighten: -35 }}",
})

-- Make selected-line highlight less bright
vim.api.nvim_set_hl(0, "CursorLineNr", {
	fg = "{{colors.secondary_fixed_dim.default.hex | lighten: -20 }}",
	bold = true,
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "{{colors.tertiary_fixed_dim.default.hex}}",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "{{colors.outline.default.hex}}",
	italic = true,
})

-- Color in other highlight groups as you see fit!
set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "{{colors.tertiary_fixed_dim.default.hex}}",
})
set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "{{colors.secondary_fixed_dim.default.hex}}",
})
set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "{{colors.primary_fixed_dim.default.hex}}",
})

-- Lualine theme, built from the same matugen colors as above.
-- Re-setup on every matugen reload so lualine's colors stay in sync.
local ok, lualine = pcall(require, "lualine")
if ok then
	local bg = "{{colors.surface.default.hex}}"
	local bg_alt = "{{colors.surface_container.default.hex}}"
	local bg_sel = "{{colors.surface_container_high.default.hex}}"
	local fg = "{{colors.on_surface.default.hex}}"
	local fg_dim = "{{colors.on_surface_variant.default.hex}}"
	local accent = "{{colors.primary_fixed_dim.default.hex}}"
	local green = "{{colors.primary_fixed_dim.default.hex}}"
	local yellow = "{{colors.secondary_fixed_dim.default.hex}}"
	local red = "{{colors.error.default.hex}}"

	lualine.setup({
		options = {
			theme = {
				normal = {
					a = { fg = bg, bg = accent, gui = "bold" },
					b = { fg = fg, bg = bg_alt },
					c = { fg = fg_dim, bg = bg },
				},
				insert = {
					a = { fg = bg, bg = green, gui = "bold" },
					b = { fg = fg, bg = bg_alt },
					c = { fg = fg_dim, bg = bg },
				},
				visual = {
					a = { fg = bg, bg = yellow, gui = "bold" },
					b = { fg = fg, bg = bg_alt },
					c = { fg = fg_dim, bg = bg },
				},
				replace = {
					a = { fg = bg, bg = red, gui = "bold" },
					b = { fg = fg, bg = bg_alt },
					c = { fg = fg_dim, bg = bg },
				},
				command = {
					a = { fg = bg, bg = accent, gui = "bold" },
					b = { fg = fg, bg = bg_alt },
					c = { fg = fg_dim, bg = bg },
				},
				inactive = {
					a = { fg = fg_dim, bg = bg_sel },
					b = { fg = fg_dim, bg = bg_sel },
					c = { fg = fg_dim, bg = bg_sel },
				},
			},
		},
	})
end
