{
  flake.modules.homeManager.apps = {
    inputs,
    config,
    pkgs,
    username,
    lib,
    ...
  }: let
    cfg = config.homeManager.apps.firefox;
    isMatugenEnabled = config.programs.matugen.enable or false;
    inherit (inputs.firefox-addons.lib.${pkgs.stdenv.hostPlatform.system}) buildFirefoxXpiAddon;
  in {
    options.homeManager.apps.firefox = {
      enable = lib.mkEnableOption "Enable firefox user profile";
      barName = lib.mkOption {
        type = lib.types.str;
        default = config.homeManager.hyprland.barName or "";
        description = "Set bar generated theme";
      };
      barTheme.enable = lib.mkEnableOption "whether to enable theme generated by bar";
    };
    config = lib.mkIf cfg.enable (lib.mkMerge [
      (lib.mkIf (cfg.barTheme.enable && cfg.barName == "dms") {
        home.activation.linkPywalfoxColors = lib.hm.dag.entryAfter ["writeBoundary"] ''
          run mkdir -p "$HOME/.cache/wal"
          run ln -sf "$HOME/.cache/wal/dank-pywalfox.json" "$HOME/.cache/wal/colors.json"
        '';
      })
      (lib.mkIf (!cfg.barTheme.enable && isMatugenEnabled) {
        home.activation.linkPywalfoxColors = lib.hm.dag.entryAfter ["writeBoundary"] ''
          run mkdir -p "$HOME/.cache/wal"
          run ln -sf "$HOME/.cache/wal/matugen-colors.json" "$HOME/.cache/wal/colors.json"
        '';
      })
      {
        home.packages = with pkgs; [pywalfox-native];
        programs.firefox = {
          enable = true;
          configPath = "${config.xdg.configHome}/mozilla/firefox";

          # pywalfox colors update
          nativeMessagingHosts = [pkgs.pywalfox-native];

          # System-level policies
          policies = {
            DisableTelemetry = true;
            DisableFirefoxStudies = true;
            DisablePocket = true;
            BlockAboutConfig = false;
            OfferToSaveLogins = false;
          };

          profiles.${username} = {
            name = username;
            isDefault = true;

            extensions.force = true; # enable overwrite
            extensions.packages = with pkgs.nur.repos.rycee.firefox-addons; [
              ublock-origin
              old-reddit-redirect
              reddit-enhancement-suite
              tree-style-tab
              don-t-fuck-with-paste
              return-youtube-dislikes
              youtube-nonstop
              darkreader
              ctrl-number-to-switch-tabs
              pywalfox
            ];

            settings = {
              # Enable theming with userChrome.css
              "toolkit.legacyUserProfileCustomizations.stylesheets" = true;

              # Clean up Firefox Home Content (New Tab Page)
              "browser.newtabpage.activity-stream.nova.enabled" = false;
              "browser.newtabpage.activity-stream.feeds.weatherfeed" = false;
              "browser.newtabpage.activity-stream.feeds.section.topstories" = false;
              "browser.newtabpage.activity-stream.feeds.topsites" = false;
              "browser.newtabpage.activity-stream.showSponsored" = false;
              "browser.newtabpage.activity-stream.showSponsoredCheckboxes" = false;
              "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
              "browser.newtabpage.activity-stream.showWeather" = false;
              "browser.newtabpage.activity-stream.showSearch" = false;
              "browser.newtabpage.activity-stream.system.showWeather" = false;
              "browser.newtabpage.activity-stream.widgets.system.weather.enabled" = false;
              "browser.newtabpage.activity-stream.widgets.weather.enabled" = false;

              # Resume previous browser session
              "browser.startup.page" = 3;
            };
          };
        };
      }
    ]);
  };
}
