config_version = 13

[accessibility]
ui_scale = 1.1000000089406967

[bar.default]
background_opacity = 0.64999998547136784
capsule = true
capsule_border = "primary"
capsule_foreground = "primary"
center = [ "group:g3" ]
end = [ "recorder", "todo", "nix-monitor", "group:g1", "group:g2" ]
font_family = "Maple Mono NF"
margin_edge = 0
margin_ends = 20
padding = 6
panel_overlap = 0
radius = 20
radius_top_left = 8
radius_top_right = 8
scale = 1.1000000000000001
shadow = false
start = [ "workspaces", "media", "audio_visualizer" ]

    [[bar.default.capsule_group]]
    border = "primary"
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g1"
    members = [ "temp", "cpu", "ram", "sysmon" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    border = "primary"
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g2"
    members = [ "network", "bluetooth" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    border = "primary"
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g3"
    members = [ "tray", "notifications", "clock", "cat" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true

[control_center]
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "audio"

    [[control_center.shortcuts]]
    type = "notification"

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.65000000000000002
enabled = true
icon_size = 35
inactive_opacity = 0.59999998658895493
item_spacing = 8
reserve_space = false
shadow = false
show_dots = true
show_instance_count = false

[hooks]
started = ""

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660.0

[keybinds]
cancel = [ "Delete", "Escape" ]

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.0
wallpaper = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@DP-5",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 910.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 910.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 288.0
    box_width = 816.0
    cx = 960.0
    cy = 668.0
    output = "DP-5"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        bands = 52
        centered = false
        color_1 = "primary"
        color_2 = "primary"
        mirrored = true
        reversed = false
        show_when_idle = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 288.0
    box_width = 816.0
    cx = 960.0
    cy = 668.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        bands = 52
        centered = false
        color_1 = "primary"
        color_2 = "primary"
        mirrored = true
        reversed = false
        show_when_idle = false

[plugin_settings."noctalia/notes"]
panel_open_near_click = true

[plugin_settings."yocraft/web-launcher"]
icon_provider = "duckduckgo"
links = [
    "Noctalia|https://docs.noctalia.dev/v5/",
    "DankMaterialShell|https://danklinux.com/docs/",
    "GitHub|https://github.com",
    "GitLab|https://gitlab.com",
    "Codeberg|https://codeberg.org",
    "YouTube|https://youtube.com"
]

[plugins]
enabled = [
    "noctalia/screen_recorder",
    "noctalia/wallhaven",
    "noctalia/bongocat",
    "noctalia/notes",
    "noctalia/kaomoji",
    "noctalia/translator",
    "avivbintangaringga/nix-monitor",
    "nightwatch75/todo",
    "yocraft/web-launcher"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
date_format = "%A, %Y %b %d"
font_family = "Maple Mono NF"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true

    [shell.panel]
    control_center_placement = "attached"
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "glass"
    wallpaper_placement = "attached"

    [shell.screen_corners]
    enabled = true
    size = 40

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl reboot --firmware-setup"
    countdown_seconds = 0.0
    enabled = true
    glyph = "cpu"
    label = "UEFI Reboot"
    shortcut = "5"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "6"
    variant = "destructive"

[system.monitor]
cpu_poll_seconds = 1
network_poll_seconds = 1

[theme]
builtin = "Ayu"
custom_palette = "m3-content"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "ghostty", "hyprland", "kitty", "niri", "qt" ]
    community_ids = [ "pywalfox", "discord", "zed" ]

        [theme.templates.user.nvim-base16]
        input_path = "~/.config/nvim/lua/matugen-template.lua"
        output_path = "~/.config/nvim/lua/matugen.lua"
        post_hook = "pkill -SIGUSR1 nvim"

[wallpaper]
directory = "/home/wyn/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

    [wallpaper.last]
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

    [wallpaper.monitors.DP-2]
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

    [wallpaper.monitors.DP-5]
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

[widget.audio_visualizer]
centered = false
width = 100.0

[widget.cat]
audio_spectrum = true
scale = 1.45
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.media]
hide_when_no_media = true
title_scroll = "always"

[widget.network]
show_label = false

[widget.nix-monitor]
show_text = false
type = "avivbintangaringga/nix-monitor:nix-monitor"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.sysmon]
stat = "disk_used_pct"

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.tray]
drawer = true
hidden = [ "network", "blueman" ]