# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  base46 = {
    pname = "base46";
    version = "cb8a1257bbc2640f6e7415a01219b34d3efd1494";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "base46";
      rev = "cb8a1257bbc2640f6e7415a01219b34d3efd1494";
      fetchSubmodules = false;
      sha256 = "sha256-6kK8q2dmmW3RO9FQmlcYN6Yyhl6fXE5ey1l8PWRVCfc=";
    };
    date = "2026-06-07";
  };
  maa-cli = {
    pname = "maa-cli";
    version = "v0.7.5";
    src = fetchFromGitHub {
      owner = "MaaAssistantArknights";
      repo = "maa-cli";
      rev = "v0.7.5";
      fetchSubmodules = false;
      sha256 = "sha256-rvFjtmsOC25t/vKgZGO6WmwtC+yxXoZKXvwd3jpoKvY=";
    };
  };
  umbrella-fetch = {
    pname = "umbrella-fetch";
    version = "v0.1.6";
    src = fetchFromGitHub {
      owner = "ezequielgk";
      repo = "Umbrella-Fetch";
      rev = "v0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-U+gANbRoYVmLz7AMog55eHl9+Sm9/EJuuAAimr8psQY=";
    };
  };
}
