# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  base46 = {
    pname = "base46";
    version = "83522e02c6c3b4ea901c4bffd9e0a5e0371c1fe6";
    src = fetchFromGitHub {
      owner = "AvengeMedia";
      repo = "base46";
      rev = "83522e02c6c3b4ea901c4bffd9e0a5e0371c1fe6";
      fetchSubmodules = false;
      sha256 = "sha256-kwDMC6rYzJYECmGnwn8JiAbffUq7hAXcUH6gPSkk2uI=";
    };
    date = "2026-07-23";
  };
  leaves = {
    pname = "leaves";
    version = "v0.2.0-cross";
    src = fetchFromGitHub {
      owner = "patonw";
      repo = "leaves";
      rev = "v0.2.0-cross";
      fetchSubmodules = false;
      sha256 = "sha256-JGWGo/JDC3/Sj97ca4CrgD4WaobYUVmbryuIg/AN2kU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-JGWGo_JDC3_Sj97ca4CrgD4WaobYUVmbryuIg_AN2kU=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  maa-cli = {
    pname = "maa-cli";
    version = "v0.7.5";
    src = fetchFromGitHub {
      owner = "MaaAssistantArknights";
      repo = "maa-cli";
      rev = "v0.7.5";
      fetchSubmodules = false;
      sha256 = "sha256-rvFjtmsOC25t/vKgZGO6WmwtC+yxXoZKXvwd3jpoKvY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-rvFjtmsOC25t_vKgZGO6WmwtC+yxXoZKXvwd3jpoKvY=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  umbrella-fetch = {
    pname = "umbrella-fetch";
    version = "v0.1.6";
    src = fetchFromGitHub {
      owner = "ezequielgk";
      repo = "Umbrella-Fetch";
      rev = "v0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-U+gANbRoYVmLz7AMog55eHl9+Sm9/EJuuAAimr8psQY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-U+gANbRoYVmLz7AMog55eHl9+Sm9_EJuuAAimr8psQY=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
}
