color0 #57404d
color1 #ffb4ab
color2 #cabeff
color3 #cabeff
color4 #f9b1dc
color5 #cabeff
color6 #cabeff
color7 #f2dde6
color8 #a58998
color9 #ffb4ab
color10 #cabeff
color11 #cabeff
color12 #f9b1dc
color13 #cabeff
color14 #cabeff
color15 #f2dde6

cursor                #f2dde6
cursor_text_color     #1b1017
background            #1b1017
foreground            #f2dde6
selection_foreground  #debece
selection_background  #57404d
active_border_color   #cabeff
inactive_border_color #57404d
url_color             #cabeff

active_tab_foreground   #322075
active_tab_background   #cabeff
inactive_tab_foreground #debece
inactive_tab_background #57404d
cursor_trail_color      #debece
