color0 #3b4857
color1 #ffb4ab
color2 #4cd9e1
color3 #80d4d9
color4 #9ecafc
color5 #4cd9e1
color6 #80d4d9
color7 #dde3ee
color8 #8492a4
color9 #ffb4ab
color10 #4cd9e1
color11 #80d4d9
color12 #9ecafc
color13 #4cd9e1
color14 #80d4d9
color15 #dde3ee

cursor                #dde3ee
cursor_text_color     #0d141c
background            #0d141c
foreground            #dde3ee
selection_foreground  #bac8db
selection_background  #3b4857
active_border_color   #4cd9e1
inactive_border_color #3b4857
url_color             #4cd9e1

active_tab_foreground   #003739
active_tab_background   #4cd9e1
inactive_tab_foreground #bac8db
inactive_tab_background #3b4857
cursor_trail_color      #bac8db
