{
  modules.homeManager.desktop = {
    config,
    lib,
    pkgs,
    ...
  }: let
    cfg = config.homeManager.desktop;
    activeWM = lib.filter (n: config.homeManager.${n}._module_marker or false) ["hyprland" "niri" "i3" "aerospace"];
    activeBar = lib.filter (n: config.homeManager.${n}._module_marker or false) ["noctalia" "dms"];
  in {
    # Placeholders for desktop environments
    options.homeManager.desktop = {
      wm = lib.mkOption {
        type = lib.types.nullOr (lib.types.enum ["hyprland" "niri" "i3" "aerospace"]);
        default = lib.head (activeWM ++ [null]);
        readOnly = true;
        description = "Currently active window manager, derived from which WM module is imported.";
      };
      bar = lib.mkOption {
        type = lib.types.nullOr (lib.types.enum ["noctalia" "dms"]);
        default = lib.head (activeBar ++ [null]);
        readOnly = true;
        description = "Currently active wayland bar, derived from which bar module is imported.";
      };
      wallpaper = lib.mkOption {
        type = lib.types.path;
        description = "Set desktop wallpaper";
      };
      terminal = lib.mkOption {
        type = lib.types.enum ["kitty" "ghostty"];
        default = "kitty";
        description = "Choose default terminal, does not install any terminal";
      };
      browser = lib.mkOption {
        type = lib.types.str;
        default = "firefox";
        description = "Choose default browser, does not install any browser";
      };
      barThemeEnabled = lib.mkEnableOption "Whether to enable theme generated by bar";
      qylockEnabled = lib.mkEnableOption "Use qylock as lockscreen, does not install qylock";
    };

    config = {
      assertions = [
        {
          assertion = lib.length activeWM <= 1;
          message = "homeManager.desktop: more than one window manager module imported (${toString activeWM}). Only one may be active.";
        }
        {
          assertion = lib.length activeBar <= 1;
          message = "homeManager.desktop: more than one bar module imported (${toString activeBar}). Only one may be active.";
        }
        {
          assertion = !cfg.barThemeEnabled || (cfg.bar != null);
          message = "homeManager.desktop.barThemeEnabled cannot be true when no bar module is active.";
        }
      ];

      home.packages = with pkgs; [
        # --- Desktop Apps ---
        mpv # Video player
        picard # Music tagger GUI
        rhythmbox # Music player GUI
        eog # GNOME Image viewer (GTK based)
        file-roller # GNOME Archive manager interface
        pavucontrol # PulseAudio/PipeWire volume panel
      ];

      home.file = {
        "Pictures/Wallpapers" = {
          source = ../../assets/wallpapers;
          force = true;
        };
        ".face".source = ../../assets/face.jpg;
      };
    };
  };
}
