{
  modules.homeManager.terminals = {
    pkgs,
    config,
    lib,
    ...
  }: let
    cfg = config.homeManager.terminals.kitty;
    isMatugenEnabled = config.programs.matugen.enable or false;
    barThemes = {
      noctalia = "include themes/noctalia.conf";
      dms = ''
        include dank-theme.conf
        include dank-tabs.conf
      '';
    };
  in {
    options.homeManager.terminals.kitty = {
      enable = lib.mkEnableOption "Enable kitty terminal";
      barName = lib.mkOption {
        type = lib.types.str;
        default = config.homeManager.hyprland.barName or "";
        description = "Set bar generated theme";
      };
      barTheme.enable = lib.mkEnableOption "whether to enable theme generated by bar";
    };
    config = lib.mkIf cfg.enable (lib.mkMerge [
      (lib.mkIf (!isMatugenEnabled) {
        programs.kitty.themeFile = "Catppuccin-Mocha";
      })
      {
        programs.kitty = {
          enable = true;
          # Upstream test failures resolved; use default kitty package (>= 0.44).
          package = pkgs.kitty;
          settings = {
            font_family = "Maple Mono NF";
            font_size = 12;
            wheel_scroll_min_lines = 1;
            window_padding_width = 4;
            confirm_os_window_close = 0;
            scrollback_lines = 10000;
            enable_audio_bell = false;
            mouse_hide_wait = 60;
            cursor_trail = 1;
            tab_fade = 1;
            active_tab_font_style = "bold";
            inactive_tab_font_style = "bold";
            tab_bar_edge = "top";
            tab_bar_margin_width = 0;
            tab_bar_style = "powerline";
            #tab_bar_style = "fade";
            enabled_layouts = "splits";
            open_url_with_default = true;
            detect_urls = true;
            allow_remote_control = true;
            remember_window_size = "no";
            initial_window_width = 1024;
            initial_window_height = 720;
            background_blur = 1;
            shell = "${pkgs.zsh}/bin/zsh";
          };

          shellIntegration.enableZshIntegration = true;
          shellIntegration.enableFishIntegration = true;
          shellIntegration.enableBashIntegration = true;
          shellIntegration.mode = "enabled";

          extraConfig = ''
            ${
              if cfg.barTheme.enable
              then (barThemes.${cfg.barName} or "")
              else if isMatugenEnabled
              then ''
                include matugen-colors.conf
              ''
              else ''
              ''
            }

            # Map missing Unicode symbols (starship) to font that has them
            symbol_map U+2190-U+21FF DejaVu Sans

            #open_url_with default
            url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty sftp ssh
            #detect_urls yes

            # Clipboard
            map ctrl+shift+v        paste_from_clipboard
            map ctrl+shift+c        copy_to_clipboard

            # Scrolling
            map ctrl+shift+up        scroll_line_up
            map ctrl+shift+down      scroll_line_down
            map ctrl+shift+k         scroll_line_up
            map ctrl+shift+j         scroll_line_down
            map ctrl+shift+page_up   scroll_page_up
            map ctrl+shift+page_down scroll_page_down
            map ctrl+shift+home      scroll_home
            map ctrl+shift+end       scroll_end
            map ctrl+shift+h         show_scrollback

            # Window management
            map alt+n               new_window_with_cwd
            #map alt+n              new_os_window
            map alt+w               close_window
            map ctrl+shift+enter    launch --location=hsplit
            map ctrl+shift+s        launch --location=vsplit
            map ctrl+shift+]        next_window
            map ctrl+shift+[        previous_window
            map ctrl+shift+f        move_window_forward
            map ctrl+shift+b        move_window_backward
            map ctrl+shift+`        move_window_to_top
            map ctrl+shift+1        first_window
            map ctrl+shift+2        second_window
            map ctrl+shift+3        third_window
            map ctrl+shift+4        fourth_window
            map ctrl+shift+5        fifth_window
            map ctrl+shift+6        sixth_window
            map ctrl+shift+7        seventh_window
            map ctrl+shift+8        eighth_window
            map ctrl+shift+9        ninth_window # Tab management
            map ctrl+shift+0        tenth_window
            map ctrl+shift+right    next_tab
            map ctrl+shift+left     previous_tab
            map ctrl+shift+t        new_tab
            map ctrl+shift+q        close_tab
            map ctrl+shift+l        next_layout
            map ctrl+shift+.        move_tab_forward
            map ctrl+shift+,        move_tab_backward

            # Miscellaneous
            map ctrl+shift+up      increase_font_size
            map ctrl+shift+down    decrease_font_size
            map ctrl+shift+backspace restore_font_size
          '';
        };
      }
    ]);
  };
}
