[bar.default]
background_opacity = 0.65000000000000002
capsule = true
capsule_border = "primary"
capsule_foreground = "primary"
center = [ "group:g3" ]
end = [ "screen_recorder", "group:g1", "group:g2" ]
margin_edge = 0
margin_ends = 12
padding = 6
panel_overlap = 0
scale = 1.1000000000000001
shadow = false
start = [ "workspaces", "media", "audio_visualizer" ]

    [[bar.default.capsule_group]]
    border = "primary"
    fill = "surface_variant"
    foreground = "primary"
    id = "g1"
    members = [ "temp", "cpu", "ram", "sysmon" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    border = "primary"
    fill = "surface_variant"
    foreground = "primary"
    id = "g2"
    members = [ "network", "bluetooth" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    border = "primary"
    fill = "surface_variant"
    foreground = "primary"
    id = "g3"
    members = [ "tray", "notifications", "clock", "bongocat" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true

[control_center]
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "keyboard_layout"

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.65000000000000002
enabled = true
icon_size = 35
inactive_opacity = 0.59999998658895493
item_spacing = 8
padding = 6
shadow = false
show_dots = true
show_instance_count = false

[hooks]
logging_out = "hyprctl dispatch exit"
started = "pkill openrgb; sleep 1; openrgb --startminimized --profile purple;"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660

[keybinds]
cancel = [ "Delete", "Escape" ]

[location]
address = "Fredericton, CA"

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@WAYLAND-1",
    "lockscreen-login-box@DP-5",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000009"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    cx = 960.0
    cy = 957.0
    output = "DP-2"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    cx = 960.0
    cy = 1013.0
    output = "DP-5"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1"]
    cx = 235.0
    cy = 128.0
    output = "WAYLAND-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    cx = 960.0
    cy = 292.5
    output = "DP-5"
    rotation = 0.0
    scale = 2.1432433128356934
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    cx = 960.0
    cy = 416.89999389648438
    output = "DP-5"
    rotation = 0.0
    scale = 0.93181818723678589
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    cx = 964.9149169921875
    cy = 180.5
    output = "DP-5"
    rotation = 0.0
    scale = 0.59472769498825073
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false
        format = "{:%Y %b %d}"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    cx = 960.0
    cy = 556.0
    output = "DP-5"
    rotation = 0.0
    scale = 1.874591588973999
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        aspect_ratio = 2.5
        background = false
        bands = 32
        centered = true
        show_when_idle = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000009]
    cx = 960.0
    cy = 791.205322265625
    output = "DP-5"
    rotation = 0.0
    scale = 1.5120406150817871
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000009.settings]
        background = false
        background_opacity = 0.68000000000000005
        hide_when_no_media = true
        layout = "horizontal"

[shell]
avatar_path = "/home/wyn/nixos/modules/home/hyprland/face.jpg"
date_format = "%A, %Y %b %d"
font_family = "Maple Mono NF"
launch_apps_as_systemd_services = true
settings_show_advanced = true
telemetry_enabled = false
ui_scale = 1.1000000000000001

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    session_placement = "centered"
    shadow = false
    transparency_mode = "glass"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true
    size = 40

    [shell.screenshot]
    directory = "/home/wyn/Pictures/Screenshots"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    glyph = "player-pause"
    label = "Suspend"
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl reboot --firmware-setup"
    enabled = true
    glyph = "cpu"
    label = "BIOS Reboot"
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "5"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "6"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.0

[system.monitor]
cpu_poll_seconds = 1
network_poll_seconds = 1

[theme]
custom_palette = "m3-content"
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "hyprland", "kitty" ]
    community_ids = [ "discord" ]

[wallpaper]
directory = "/home/wyn/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/wyn/Pictures/Wallpapers/interlude_109.png"

    [wallpaper.last]
    path = "/home/wyn/Pictures/Wallpapers/interlude_109.png"

    [wallpaper.monitors.DP-5]
    path = "/home/wyn/Pictures/Wallpapers/interlude_109.png"

[weather]
address = "Fredericton, CA"

[widget.audio_visualizer]
centered = false
width = 100.0

[widget.bongocat]
audio_spectrum = true
scale = 1.3
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"

[widget.media]
hide_when_no_media = true
title_scroll = "always"

[widget.network]
show_label = false

[widget.screen_recorder]
hot_reload = true
script = "scripts/screen_recorder.lua"
type = "scripted"
video_source = "DP-5"

[widget.sysmon]
stat = "disk_pct"

[widget.tray]
drawer = true
hidden = [ "network", "blueman" ]