[bar.default]
background_opacity = 0.75
capsule = true
capsule_border = "primary"
capsule_foreground = "primary"
center = [ "tray", "clock", "workspaces", "bongocat", "notifications" ]
end = [ "temp", "cpu", "ram", "sysmon", "volume", "brightness", "bluetooth", "network" ]
margin_edge = 0
margin_ends = 0
radius = 0
start = [ "audio_visualizer", "media" ]
thickness = 30

[brightness]
enable_ddcutil = true

[control_center]
sidebar = "full"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "keyboard_layout"

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.75
enabled = true
icon_size = 35
inactive_opacity = 0.59999998658895493
show_dots = true
show_instance_count = false

[hooks]
logging_out = "hyprctl dispatch exit"
started = "pkill openrgb; sleep 1; openrgb --startminimized --profile purple;"

[shell]
avatar_path = "/home/wyn/Pictures/avatars/jeannedArc-riyo-zoom.jpg"
date_format = "%A, %Y %b %d"
launch_apps_as_systemd_services = true
settings_show_advanced = true
telemetry_enabled = false

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    session_placement = "floating"
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    glyph = "player-pause"
    label = "Suspend"
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl reboot --firmware-setup"
    enabled = true
    glyph = "cpu"
    label = "BIOS Reboot"
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "5"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "6"
    variant = "destructive"

[theme]
custom_palette = "m3-content"
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "kitty" ]
    community_ids = [ "spicetify", "discord" ]

[wallpaper]
directory = "/home/wyn/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/wyn/Pictures/Wallpapers/interlude_109.png"

    [wallpaper.last]
    path = "/home/wyn/Pictures/Wallpapers/interlude_109.png"

    [wallpaper.monitors.DP-5]
    path = "/home/wyn/Pictures/Wallpapers/interlude_109.png"

[weather]
address = "Fredericton, CA"

[widget.audio_visualizer]
bands = 20
width = 200.0

[widget.bongocat]
audio_spectrum = true
input_device = ""
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"

[widget.media]
hide_when_no_media = true
max_length = 150
title_scroll = "always"

[widget.network]
show_label = false

[widget.screen_recorder]
script = "scripts/screen_recorder.lua"
type = "scripted"
video_source = "DP-5"

[widget.sysmon]
stat = "disk_pct"

[widget.tray]
drawer = true
hidden = [ "network", "blueman" ]

[widget.workspaces]
anchor = true