[bar.default]
background_opacity = 0.65000000000000002
capsule = true
capsule_border = "primary"
capsule_foreground = "primary"
center = [ "group:g3" ]
end = [ "recorder", "group:g1", "group:g2" ]
font_family = "Maple Mono NF"
margin_edge = 0
margin_ends = 12
padding = 6
panel_overlap = 0
radius = 20
scale = 1.1000000000000001
shadow = false
start = [ "workspaces", "media", "audio_visualizer" ]

    [[bar.default.capsule_group]]
    border = "primary"
    fill = "surface_variant"
    foreground = "primary"
    id = "g1"
    members = [ "temp", "cpu", "ram", "sysmon" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    border = "primary"
    fill = "surface_variant"
    foreground = "primary"
    id = "g2"
    members = [ "network", "bluetooth" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    border = "primary"
    fill = "surface_variant"
    foreground = "primary"
    id = "g3"
    members = [ "tray", "notifications", "clock", "cat" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true

[control_center]
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "audio"

[desktop_widgets]
schema_version = 1
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.65000000000000002
enabled = true
icon_size = 35
inactive_opacity = 0.59999998658895493
item_spacing = 8
padding = 6
reserve_space = false
shadow = false
show_dots = true
show_instance_count = false

[hooks]
logging_out = "hyprctl dispatch 'hl.dsp.exit()'"
rebooting = "hyprctl dispatch 'hl.dsp.exit()'"
shutting_down = "hyprctl dispatch 'hl.dsp.exit()'"
started = ""

[keybinds]
cancel = [ "Delete", "Escape" ]

[location]
address = "Fredericton, CA"

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@WAYLAND-1",
    "lockscreen-login-box@DP-5",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000009"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 1013.0
    output = "DP-5"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 235.0
    cy = 128.0
    output = "WAYLAND-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 292.5
    output = "DP-5"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 416.89999389648438
    output = "DP-5"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 0.0
    box_width = 0.0
    cx = 964.9149169921875
    cy = 180.5
    output = "DP-5"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false
        format = "{:%Y %b %d}"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 556.0
    output = "DP-5"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        aspect_ratio = 2.5
        background = false
        bands = 32
        centered = true
        show_when_idle = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000009]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 791.205322265625
    output = "DP-5"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000009.settings]
        background = false
        background_opacity = 0.68000000000000005
        hide_when_no_media = true
        layout = "horizontal"

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/screen_recorder", "noctalia/wallhaven" ]

[system.monitor]
cpu_poll_seconds = 1
network_poll_seconds = 1

[theme]
builtin = "Ayu"
custom_palette = "m3-content"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "ghostty", "hyprland", "kitty", "qt" ]
    community_ids = [ "pywalfox", "neovim", "zed", "discord" ]

[wallpaper]
directory = "/home/wyn/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

    [wallpaper.last]
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

    [wallpaper.monitors.DP-2]
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"

    [wallpaper.monitors.DP-5]
    path = "/home/wyn/Pictures/Wallpapers/Ishtar.jpg"

    [[wallpaper.favorite]]
    path = "/home/wyn/Pictures/Wallpapers/SnakeNewYear.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/wyn/Pictures/Wallpapers/voyager.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/wyn/Pictures/Wallpapers/Amiya19birthday.jpeg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/wyn/Pictures/Wallpapers/interlude_MDxBA_1.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/wyn/Pictures/Wallpapers/Embraced_A.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/wyn/Pictures/Wallpapers/IS-Mysterious_Banquet.png"
    theme_mode = "auto"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    path = "/home/wyn/Pictures/Wallpapers/Ereshkigal.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/wyn/Pictures/Wallpapers/Frankenstein.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/wyn/Pictures/Wallpapers/Ishtar.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/wyn/Pictures/Wallpapers/IS5-Expansion-Official-Artwork.jpeg"
    theme_mode = "dark"
    wallpaper_scheme = "faithful"

    [[wallpaper.favorite]]
    path = "/home/wyn/Pictures/Wallpapers/HokusaiWin7.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/wyn/Pictures/Wallpapers/interlude_109.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/wyn/Pictures/Wallpapers/interlude_RinLen_5.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

[weather]
address = "Fredericton, CA"

[widget.audio_visualizer]
centered = false
width = 100.0

[widget.bongocat]
audio_spectrum = true
scale = 1.3
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"

[widget.cat]
audio_spectrum = true
scale = 1.45
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.media]
hide_when_no_media = true
title_scroll = "always"

[widget.network]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.screen_recorder]
hot_reload = true
script = "scripts/screen_recorder.lua"
type = "scripted"
video_source = "DP-5"

[widget.sysmon]
stat = "disk_pct"

[widget.tray]
drawer = true
hidden = [ "network", "blueman" ]