name: update flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # every Saturday at 00:00 UTC

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'xuwyn/nix-config' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - uses: cachix/install-nix-action@v31

      - name: Update flake.lock 
        run: |
          nix flake update --accept-flake-config 2> log_raw
          grep -A 2 '^•' log_raw > log || true

      - name: Parse commit message body
        run: |
          delim=$(openssl rand -hex 8)
          echo "COMMIT_MSG<<$delim" >> $GITHUB_ENV
          echo "chore(flake): update flake.lock" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          cat log >> $GITHUB_ENV
          echo "$delim" >> $GITHUB_ENV

      - name: Remove log
        run: rm -rf log log_raw

      - uses: peter-evans/create-pull-request@v8
        with: 
          title: "chore(flake): update flake.lock" 
          branch: flake-update
          commit-message: ${{ env.COMMIT_MSG }}
          labels: |
            dependencies
            automated
