name: update flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # every Saturday at 00:00 UTC

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: nix flake update
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(flake): update flake.lock"
          pr-labels: |
            dependencies
            automated
